#!/bin/sh
#
# init script for ship-it
#

### BEGIN INIT INFO
# Provides:          serial2ws
# Required-Start:    $local_fs $remote_fs $syslog $network
# Required-Stop:     $local_fs $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts serial2ws
# Description:       starts serial2ws
### END INIT INFO

TZ='Europe/Berlin';
export TZ

pypy_dir=/home/pi/install/pypy-2.6.1-linux-armhf-raspbian/bin
pypy=/home/pi/install/pypy-2.6.1-linux-armhf-raspbian/bin/pypy
gsv6ToWamp_dir=/home/pi/gsv-6ToWAMP

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME=serial2ws
DAEMON=${gsv6ToWamp_dir}/serial2ws.py
DAEMONARGS=""
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

. /lib/lsb/init-functions

test -f $DAEMON || exit 0

case "$1" in
    start)
        start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --chdir $gsv6ToWamp_dir --startas /bin/bash -- -c "exec $pypy $DAEMON $DAEMONARGS > $LOGFILE 2>&1"
        log_end_msg $?
        ;;
    stop)
        start-stop-daemon --stop --pidfile $PIDFILE
        log_end_msg $?
        rm -f $PIDFILE
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    status)
        start-stop-daemon --status --pidfile $PIDFILE
        log_end_msg $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 2
        ;;
esac

exit 0